module.exports = {
  lastUpdate: '2020-03-28T10:31:00-04:00',
  total: { slug: 'united-states', name: 'United States', infectionRate: '1.218', image: 'united-states.svg' },
  regions: [
    { slug: 'alabama', name: 'Alabama', infectionRate: '1.119' },
    { slug: 'alaska', name: 'Alaska', infectionRate: '1.034' },
    { slug: 'arizona', name: 'Arizona', infectionRate: '1.236' },
    { slug: 'arkansas', name: 'Arkansas', infectionRate: '1.121' },
    { slug: 'california', name: 'California', infectionRate: '1.163' },
    { slug: 'colorado', name: 'Colorado', infectionRate: '1.002' },
    { slug: 'connecticut', name: 'Connecticut', infectionRate: '1.216' },
    { slug: 'delaware', name: 'Delaware', infectionRate: '1.202' },
    { slug: 'district-of-columbia', name: 'District of Columbia', infectionRate: '1.148' },
    { slug: 'florida', name: 'Florida', infectionRate: '1.187' },
    { slug: 'georgia', name: 'Georgia', infectionRate: '1.238' },
    { slug: 'hawaii', name: 'Hawaii', infectionRate: '1.104' },
    { slug: 'idaho', name: 'Idaho', infectionRate: '1.288' },
    { slug: 'illinois', name: 'Illinois', infectionRate: '1.161' },
    { slug: 'indiana', name: 'Indiana', infectionRate: '1.341' },
    { slug: 'iowa', name: 'Iowa', infectionRate: '1.238' },
    { slug: 'kansas', name: 'Kansas', infectionRate: '1.165' },
    { slug: 'kentucky', name: 'Kentucky', infectionRate: '1.179' },
    { slug: 'louisiana', name: 'Louisiana', infectionRate: '1.160' },
    { slug: 'maine', name: 'Maine', infectionRate: '1.077' },
    { slug: 'maryland', name: 'Maryland', infectionRate: '1.248' },
    { slug: 'massachusetts', name: 'Massachusetts', infectionRate: '1.254' },
    { slug: 'michigan', name: 'Michigan', infectionRate: '1.217' },
    { slug: 'minnesota', name: 'Minnesota', infectionRate: '1.131' },
    { slug: 'mississippi', name: 'Mississippi', infectionRate: '1.162' },
    { slug: 'missouri', name: 'Missouri', infectionRate: '1.219' },
    { slug: 'montana', name: 'Montana', infectionRate: '1.174' },
    { slug: 'nebraska', name: 'Nebraska', infectionRate: '1.098' },
    { slug: 'nevada', name: 'Nevada', infectionRate: '1.216' },
    { slug: 'new-hampshire', name: 'New Hampshire', infectionRate: '1.133' },
    { slug: 'new-jersey', name: 'New Jersey', infectionRate: '1.221' },
    { slug: 'new-mexico', name: 'New Mexico', infectionRate: '1.169' },
    { slug: 'new-york', name: 'New York', infectionRate: '1.156' },
    { slug: 'north-carolina', name: 'North Carolina', infectionRate: '1.168' },
    { slug: 'north-dakota', name: 'North Dakota', infectionRate: '1.250' },
    { slug: 'ohio', name: 'Ohio', infectionRate: '1.237' },
    { slug: 'oklahoma', name: 'Oklahoma', infectionRate: '1.230' },
    { slug: 'oregon', name: 'Oregon', infectionRate: '1.240' },
    { slug: 'pennsylvania', name: 'Pennsylvania', infectionRate: '1.235' },
    { slug: 'rhode-island', name: 'Rhode Island', infectionRate: '1.187' },
    { slug: 'south-carolina', name: 'South Carolina', infectionRate: '1.218' },
    { slug: 'south-dakota', name: 'South Dakota', infectionRate: '1.207' },
    { slug: 'tennessee', name: 'Tennessee', infectionRate: '1.168' },
    { slug: 'texas', name: 'Texas', infectionRate: '1.193' },
    { slug: 'utah', name: 'Utah', infectionRate: '1.161' },
    { slug: 'vermont', name: 'Vermont', infectionRate: '1.141' },
    { slug: 'virginia', name: 'Virginia', infectionRate: '1.232' },
    { slug: 'washington', name: 'Washington', infectionRate: '1.078' },
    { slug: 'west-virginia', name: 'West Virginia', infectionRate: '1.316' },
    { slug: 'wisconsin', name: 'Wisconsin', infectionRate: '1.214' },
    { slug: 'wyoming', name: 'Wyoming', infectionRate: '1.243' },
    { slug: 'puerto-rico', name: 'Puerto Rico', infectionRate: '1.190' },
  ]
}