module.exports = {
  lastUpdate: '2020-03-28T20:18:00-04:00',
  total: { slug: 'united-states', name: 'United States', infectionRate: '1.161', image: 'united-states.svg' },
  regions: [
    { slug: 'alabama', name: 'Alabama', infectionRate: '1.154' },
    { slug: 'alaska', name: 'Alaska', infectionRate: '1.318' },
    { slug: 'arizona', name: 'Arizona', infectionRate: '1.140' },
    { slug: 'arkansas', name: 'Arkansas', infectionRate: '1.068' },
    { slug: 'california', name: 'California', infectionRate: '1.086' },
    { slug: 'colorado', name: 'Colorado', infectionRate: '1.176' },
    { slug: 'connecticut', name: 'Connecticut', infectionRate: '1.153' },
    { slug: 'delaware', name: 'Delaware', infectionRate: '1.238' },
    { slug: 'district-of-columbia', name: 'District of Columbia', infectionRate: '1.109' },
    { slug: 'florida', name: 'Florida', infectionRate: '1.229' },
    { slug: 'georgia', name: 'Georgia', infectionRate: '1.155' },
    { slug: 'hawaii', name: 'Hawaii', infectionRate: '1.289' },
    { slug: 'idaho', name: 'Idaho', infectionRate: '1.124' },
    { slug: 'illinois', name: 'Illinois', infectionRate: '1.134' },
    { slug: 'indiana', name: 'Indiana', infectionRate: '1.206' },
    { slug: 'iowa', name: 'Iowa', infectionRate: '1.211' },
    { slug: 'kansas', name: 'Kansas', infectionRate: '1.226' },
    { slug: 'kentucky', name: 'Kentucky', infectionRate: '1.234' },
    { slug: 'louisiana', name: 'Louisiana', infectionRate: '1.172' },
    { slug: 'maine', name: 'Maine', infectionRate: '1.204' },
    { slug: 'maryland', name: 'Maryland', infectionRate: '1.221' },
    { slug: 'massachusetts', name: 'Massachusetts', infectionRate: '1.239' },
    { slug: 'michigan', name: 'Michigan', infectionRate: '1.218' },
    { slug: 'minnesota', name: 'Minnesota', infectionRate: '1.102' },
    { slug: 'mississippi', name: 'Mississippi', infectionRate: '1.127' },
    { slug: 'missouri', name: 'Missouri', infectionRate: '1.203' },
    { slug: 'montana', name: 'Montana', infectionRate: '1.155' },
    { slug: 'nebraska', name: 'Nebraska', infectionRate: '1.146' },
    { slug: 'nevada', name: 'Nevada', infectionRate: '1.144' },
    { slug: 'new-hampshire', name: 'New Hampshire', infectionRate: '1.155' },
    { slug: 'new-jersey', name: 'New Jersey', infectionRate: '1.207' },
    { slug: 'new-mexico', name: 'New Mexico', infectionRate: '1.346' },
    { slug: 'new-york', name: 'New York', infectionRate: '1.144' },
    { slug: 'north-carolina', name: 'North Carolina', infectionRate: '1.130' },
    { slug: 'north-dakota', name: 'North Dakota', infectionRate: '1.277' },
    { slug: 'ohio', name: 'Ohio', infectionRate: '1.191' },
    { slug: 'oklahoma', name: 'Oklahoma', infectionRate: '1.146' },
    { slug: 'oregon', name: 'Oregon', infectionRate: '1.132' },
    { slug: 'pennsylvania', name: 'Pennsylvania', infectionRate: '1.176' },
    { slug: 'rhode-island', name: 'Rhode Island', infectionRate: '1.210' },
    { slug: 'south-carolina', name: 'South Carolina', infectionRate: '1.151' },
    { slug: 'south-dakota', name: 'South Dakota', infectionRate: '1.179' },
    { slug: 'tennessee', name: 'Tennessee', infectionRate: '1.147' },
    { slug: 'texas', name: 'Texas', infectionRate: '1.128' },
    { slug: 'utah', name: 'Utah', infectionRate: '1.211' },
    { slug: 'vermont', name: 'Vermont', infectionRate: '1.216' },
    { slug: 'virginia', name: 'Virginia', infectionRate: '1.128' },
    { slug: 'washington', name: 'Washington', infectionRate: '1.180' },
    { slug: 'west-virginia', name: 'West Virginia', infectionRate: '1.137' },
    { slug: 'wisconsin', name: 'Wisconsin', infectionRate: '1.208' },
    { slug: 'wyoming', name: 'Wyoming', infectionRate: '1.122' },
    { slug: 'puerto-rico', name: 'Puerto Rico', infectionRate: '1.146' },
  ]
}